services:
  bmz-auth:
    build:
      context: ./auth
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=auth.settings
      - DEBUG=True
    networks:
      - bmz_network
  bmz-prod:
    build:
      context: ./products
    ports:
      - "8001:8001"
    environment:
      - AUTH_SERVICE_URL=http://bmz-auth:8000
      - DJANGO_SETTINGS_MODULE=products_project.settings
      - DEBUG=True
    depends_on:
      - bmz-auth
    networks:
      - bmz_network
  bmz-cart:
    build:
      context: ./cart
    ports:
      - "8002:8002"
    environment:
      - AUTH_SERVICE_URL=http://bmz-auth:8000
      - DJANGO_SETTINGS_MODULE=cart_project.settings
      - DEBUG=True
    depends_on:
      - bmz-auth
    networks:
      - bmz_network
  bmz-orders:
    build:
      context: ./orders
    ports:
      - "8003:8003"
    environment:
      - AUTH_SERVICE_URL=http://bmz-auth:8000
      - CART_SERVICE_URL=http://bmz-cart:8002
      - PRODUCTS_SERVICE_URL=http://bmz-prod:8001
      - DJANGO_SETTINGS_MODULE=orders_project.settings
      - DEBUG=True
    depends_on:
      - bmz-auth
    networks:
      - bmz_network
  bmz-otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: bmz-otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the Collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension
    networks:
      - bmz_network
  bmz-jaeger:
    container_name: bmz-jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    networks:
      - bmz_network

networks:
  bmz_network: